name: Publish project
on:
  issues:
    types:
      - labeled
jobs:
  publish-project:
    if: github.event.label.name == 'accepted'
    runs-on: ubuntu-latest
    env:
      ISSUE_USER: ${{ github.event.issue.user.login }}
      ISSUE_BODY: ${{ github.event.issue.body }}

    steps:
      - uses: actions/checkout@v2

      - name: Shows issue
        run: |
          echo $ISSUE_USER
          echo $ISSUE_BODY

      - name: Run script
        run: python .github/scripts/publish.py >> $GITHUB_ENV

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Project published. thanks, @${{env.ISSUE_USER}}!"

      - name: Remove publication-request label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            accepted
            publication-request

      - name: Add published label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: published

      - name: Add reaction to issue
        uses: aidan-mundy/react-to-issue@v1.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          reactions: heart, hooray

      - name: Close issue
        uses: peter-evans/close-issue@v1.0.3
        with:
          comment: |
            Thanks for publishing your project!
            You can check your project page [here](https://atta.brenocq.com/projects/${{ env.PROJECT_PATH }}).
            Your web build is available [here](https://atta.brenocq.com/projects/${{ env.PROJECT_PATH }}/build).
            Now anyone can open your project from the atta engine too! `File>Open>From published`.
